apiVersion: v1
kind: ConfigMap
metadata:
  name: sif-viz-component-configmap
  labels:
    app: sif-viz-component
data:
  INFLUXDB_HOST: http://influx.iot.svc.cluster.local:8086
  INFLUXDB_USER: admin
  INFLUXDB_PASS: secure_influx_iot_user
